services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - 6379:6379

  solr:
    image: solr:8
    container_name: solr
    ports:
      - 8983:8983
    volumes:
      - solr_data:/var/solr
    command:
      - solr-precreate
      - alunos

  airflow-init:
    build: .
    depends_on:
      - postgres
      - redis
      - solr
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW_DADOS_PATH: /opt/airflow/dados
      SOLR_URL: http://solr:8983/solr/alunos
    entrypoint: >
      bash -c "
        echo 'Inicializando o banco de dados...' &&
        airflow db init &&
        airflow users create --username admin --password admin --firstname Admin --lastname Admin --role Admin --email admin@example.com
      "

  airflow-webserver:
    build: .
    depends_on:
      - airflow-init
    ports:
      - 8080:8080
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dados:/opt/airflow/dados
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW_DADOS_PATH: /opt/airflow/dados
      SOLR_URL: http://solr:8983/solr/alunos
    command: webserver

  airflow-scheduler:
    build: .
    depends_on:
      - airflow-webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dados:/opt/airflow/dados
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW_DADOS_PATH: /opt/airflow/dados
      SOLR_URL: http://solr:8983/solr/alunos
    command: scheduler

  airflow-worker:
    build: .
    depends_on:
      - airflow-webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dados:/opt/airflow/dados
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW_DADOS_PATH: /opt/airflow/dados
      SOLR_URL: http://solr:8983/solr/alunos
    command: celery worker

volumes:
  postgres_db:
  solr_data:
